# Generated by Django 5.2.4 on 2026-03-12 19:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=150)),
                ('size_bytes', models.BigIntegerField()),
                ('storage_key', models.CharField(max_length=500)),
                ('checksum', models.CharField(max_length=128)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task')),
                ('uploaded_by_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attachments',
                'indexes': [models.Index(fields=['task'], name='idx_attachments_task_id')],
                'constraints': [models.CheckConstraint(condition=models.Q(('size_bytes__lte', 26214400)), name='ck_attachments_size_bytes')],
            },
        ),
    ]
