# Generated by Django 5.2.4 on 2026-03-12 19:39

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=80)),
                ('target_type', models.CharField(max_length=80)),
                ('target_id', models.UUIDField()),
                ('metadata_json', models.JSONField(default=dict)),
                ('request_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='activity_logs', to='organizations.organization')),
            ],
            options={
                'db_table': 'activity_logs',
                'indexes': [models.Index(fields=['organization', 'created_at'], name='idx_actlog_org_created'), models.Index(fields=['actor_user', 'created_at'], name='idx_actlog_actor_created'), models.Index(fields=['event_type'], name='idx_activity_logs_event_type'), django.contrib.postgres.indexes.GinIndex(fields=['metadata_json'], name='idx_activity_logs_metadata_gin')],
            },
        ),
    ]
