# Generated by Django 5.2.12 on 2026-03-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='request_id',
            field=models.CharField(max_length=64),
        ),
    ]
